title: Florian Meyer
author:
  name: Florian Meyer
  email: florian.meyer.hh@gmail.com
description: >-
  Florian Meyer is a software engineer specializing in full-stack development and microservice architecture, with a strong passion for AI and modern, innovative work methodologies.
baseurl: ""
url: ""


collections:
  publications:
    output: true
  projects:
    output: true
